project_id = "vnysbpnggnplvgkfokin"
[api]
port = 54321
[db]
port = 54322
[studio]
port = 54323
[inbucket]
port = 54324

[functions.crm-sync-properties]
enabled = true
verify_jwt = false
import_map = "./functions/crm-sync-properties/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crm-sync-properties/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crm-sync-properties/*.html" ]

[functions.generate-property-embedding]
enabled = true
verify_jwt = false
import_map = "./functions/generate-property-embedding/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-property-embedding/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-property-embedding/*.html" ]
